# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (c) 2026 CommonHuman-Lab
"""
Tests for engine/waf_detect.py — WAF fingerprinting.
"""

from unittest.mock import MagicMock

import pytest

from stingxss.engine import waf_detect
from stingxss.engine.waf_detect import (
    WafResult,
    EVASION_NONE,
    detect,
)


def _make_injector(status: int, headers: dict, body: str) -> MagicMock:
    """Return a mock Injector whose .get() returns a canned response."""
    resp = MagicMock()
    resp.status_code = status
    resp.headers     = headers
    resp.text        = body

    injector = MagicMock()
    injector.get.return_value = resp
    return injector


class TestDetect:
    URL = "https://example.com/search?q=test"

    def test_no_waf_when_payload_reflected(self):
        injector = _make_injector(
            200, {}, "<script>alert(1)</script> found"
        )
        result = detect(injector, self.URL)
        assert result.detected is False
        assert result.confidence == "none"

    def test_cloudflare_detected_via_header(self):
        injector = _make_injector(
            403,
            {"cf-ray": "abc123", "server": "cloudflare"},
            "Attention Required | Cloudflare",
        )
        result = detect(injector, self.URL)
        assert result.detected is True
        assert result.name == "Cloudflare"
        assert result.confidence in ("high", "medium")

    def test_generic_waf_on_403(self):
        injector = _make_injector(403, {}, "Forbidden")
        result = detect(injector, self.URL)
        assert result.detected is True
        assert result.name == "Generic WAF"
        assert result.confidence == "low"

    def test_no_waf_on_clean_200(self):
        injector = _make_injector(200, {}, "Welcome to our site")
        result = detect(injector, self.URL)
        assert result.detected is False

    def test_exception_returns_no_waf(self):
        injector = MagicMock()
        injector.get.side_effect = Exception("connection refused")
        result = detect(injector, self.URL)
        assert result.detected is False
        assert EVASION_NONE in result.evasions

    def test_modsecurity_detected_via_body(self):
        injector = _make_injector(
            406,
            {"server": "Apache/mod_security"},
            "Not Acceptable! This error was generated by Mod_Security",
        )
        result = detect(injector, self.URL)
        assert result.detected is True
        assert result.name == "ModSecurity"

    def test_evasions_are_list(self):
        injector = _make_injector(403, {"cf-ray": "x", "server": "cloudflare"}, "")
        result = detect(injector, self.URL)
        assert isinstance(result.evasions, list)
        assert len(result.evasions) >= 1


class TestWafResult:
    def test_dataclass_fields(self):
        r = WafResult(detected=True, name="Test", evasions=["none"], confidence="high")
        assert r.detected is True
        assert r.name == "Test"
