# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (c) 2026 CommonHuman-Lab
"""Source and sink pattern tables for DOM XSS analysis."""

from typing import List, Tuple

# Attacker-controllable sources
SOURCES: List[Tuple[str, str]] = [
  (r"location\.hash",                                              "location.hash"),
  (r"location\.search",                                            "location.search"),
  (r"location\.href",                                              "location.href"),
  (r"location\.pathname",                                          "location.pathname"),
  (r"window\.location(?![\.\[])",                                  "window.location"),
  (r"document\.referrer",                                          "document.referrer"),
  (r"document\.URL\b",                                             "document.URL"),
  (r"document\.baseURI",                                           "document.baseURI"),
  (r"document\.documentURI",                                       "document.documentURI"),
  (r"document\.URLUnencoded",                                      "document.URLUnencoded"),
  (r"document\.cookie",                                            "document.cookie"),
  (r"document\.domain",                                            "document.domain"),
  (r"window\.name",                                                "window.name"),
  (r"history\.state",                                              "history.state"),
  (r"postMessage",                                                  "postMessage"),
  (r"addEventListener\s*\(\s*['\"]message['\"]",                   "postMessage"),
  (r"\bmsg\.data\b",                                               "msg.data"),
  (r"\be\.data\b",                                                 "e.data"),
  (r"URLSearchParams",                                             "URLSearchParams"),
  (r"localStorage\.getItem",                                       "localStorage.getItem"),
  (r"localStorage\[",                                              "localStorage[key]"),
  (r"localStorage\.[a-zA-Z_$][\w$]*(?!\s*[\(\[])",                "localStorage.property"),
  (r"sessionStorage\.getItem",                                     "sessionStorage.getItem"),
  (r"sessionStorage\[",                                            "sessionStorage[key]"),
  (r"sessionStorage\.[a-zA-Z_$][\w$]*(?!\s*[\(\[])",              "sessionStorage.property"),
  (r"\bwindow\.status\b",                                          "window.status"),
  (r"\be\.target\.value\b",                                        "e.target.value"),
  (r"\bmsg\.data\.\w+",                                            "msg.data.*"),
  (r"frames\[",                                                    "frames[n].name"),
]

# Dangerous execution / rendering sinks
SINKS: List[Tuple[str, str]] = [
  (r"\.innerHTML\s*=",                                             "innerHTML"),
  (r"\.outerHTML\s*=",                                             "outerHTML"),
  (r"\.insertAdjacentHTML\s*\(",                                   "insertAdjacentHTML"),
  (r"document\.write\s*\(",                                        "document.write"),
  (r"document\.writeln\s*\(",                                      "document.writeln"),
  (r"\beval\s*\(",                                                 "eval"),
  (r"setTimeout\s*\(\s*['\"`]",                                    "setTimeout(string)"),
  (r"setTimeout\s*\(\s*(?!function\b)[a-zA-Z_$][\w$]*\s*,",       "setTimeout(variable)"),
  (r"setInterval\s*\(\s*['\"`]",                                   "setInterval(string)"),
  (r"new\s+Function\s*\(",                                         "new Function()"),
  (r"\.setAttribute\s*\(\s*['\"]on",                               "setAttribute(on...)"),
  (r"\.setAttribute\s*\(\s*['\"]src",                              "setAttribute(src)"),
  (r"\.setAttribute\s*\(\s*['\"]href",                             "setAttribute(href)"),
  (r"\.setAttribute\s*\(\s*['\"]action",                           "setAttribute(action)"),
  (r"\.createContextualFragment\s*\(",                             "createContextualFragment"),
  (r"location\.href\s*=",                                          "location.href="),
  (r"(?<!location)\.href\s*=",                                     ".href="),
  (r"document\.location\s*=",                                      "document.location="),
  (r"location\.replace\s*\(",                                      "location.replace()"),
  (r"location\.assign\s*\(",                                       "location.assign()"),
  (r"window\.open\s*\(",                                           "window.open()"),
  (r"\.src\s*=",                                                   ".src="),
  (r"\.srcdoc\s*=",                                                ".srcdoc="),
  (r"\.action\s*=",                                                ".action="),
  (r"\.formAction\s*=",                                            ".formAction="),
  (r"\.data\s*=",                                                  ".data="),
  (r"\$\s*\(\s*['\"`][^'\"`]*location",                            "jQuery(location...)"),
  (r"\.html\s*\(",                                                 "jQuery.html()"),
  (r"dangerouslySetInnerHTML",                                     "React dangerouslySetInnerHTML"),
  (r"document\.execCommand\s*\(",                                  "document.execCommand"),
  (r"\$\$?\.globalEval\s*\(",                                      "$.globalEval()"),
  (r"angular\.element.*\.html\s*\(",                               "angular.html()"),
  (r"(?:\$parse\s*\(|get\s*\(\s*['\"]?\$parse['\"]?\s*\))",       "$parse()"),
  (r"\bfetch\s*\(",                                                "fetch()"),
  (r"(?:xhttp|xhr|req)\s*\.open\s*\(",                            "xhr.open()"),
  (r"\.setAttributeNS\s*\(",                                       "setAttributeNS()"),
  # javascript: URI sinks — attacker controls a URL-type attribute or navigation target
  (r"\.href\s*=\s*[^=]",                                          ".href= (nav)"),
  (r"\.action\s*=\s*[^=]",                                        ".action= (nav)"),
  (r"\.formAction\s*=\s*[^=]",                                    ".formAction= (nav)"),
  (r"location\s*=\s*[^=]",                                        "location= (nav)"),
  (r"document\.location\s*=\s*[^=]",                              "document.location= (nav)"),
]
