# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (c) 2026 CommonHuman-Lab
"""
StingXSS — engine/waf_detect.py
WAF fingerprinting and evasion strategy selection.

Probes the target with a known-bad payload and analyses the response
(status code, headers, body) to identify the WAF in front of it.
Returns the WAF name and an ordered list of evasion strategies to try.
"""

from __future__ import annotations

import re
import urllib.parse as up
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Tuple

# ---------------------------------------------------------------------------
# Evasion strategy names (used by payload_gen to pick encoding transforms)
# ---------------------------------------------------------------------------
EVASION_NONE          = "none"
EVASION_CASE_MIXING   = "case_mixing"
EVASION_HTML_ENCODE   = "html_encode"
EVASION_UNICODE       = "unicode_escape"
EVASION_DOUBLE_ENCODE = "double_encode"
EVASION_CHUNKED_TAGS  = "chunked_tags"
EVASION_NULL_BYTE     = "null_byte"
EVASION_NEWLINE       = "newline_inject"
EVASION_COMMENT_BREAK = "comment_break"
EVASION_BACKTICK      = "backtick_attr"


# ---------------------------------------------------------------------------
# WAF signatures
# Each entry: (waf_name, [(header_name, regex), ...], [body_regex, ...], [status_codes])
# ---------------------------------------------------------------------------

@dataclass
class WafSignature:
  name:         str
  header_clues: List[Tuple[str, str]] = field(default_factory=list)  # (header, regex)
  body_clues:   List[str]             = field(default_factory=list)  # body regexes
  status_codes: List[int]             = field(default_factory=list)
  evasions:     List[str]             = field(default_factory=list)  # recommended evasion order


_SIGNATURES: List[WafSignature] = [
  WafSignature(
    name="Cloudflare",
    header_clues=[
      ("server",       r"cloudflare"),
      ("cf-ray",       r".+"),
      ("cf-cache-status", r".+"),
    ],
    body_clues=[r"cloudflare", r"cf-ray", r"Attention Required"],
    status_codes=[403, 503],
    evasions=[EVASION_UNICODE, EVASION_CASE_MIXING, EVASION_COMMENT_BREAK, EVASION_NEWLINE],
  ),
  WafSignature(
    name="Akamai",
    header_clues=[
      ("server",         r"AkamaiGHost"),
      ("x-check-cacheable", r".+"),
    ],
    body_clues=[r"Access Denied", r"Reference #\d+\.\w+"],
    status_codes=[403],
    evasions=[EVASION_HTML_ENCODE, EVASION_DOUBLE_ENCODE, EVASION_CHUNKED_TAGS],
  ),
  WafSignature(
    name="Imperva",
    header_clues=[
      ("x-iinfo",       r".+"),
      ("x-cdn",         r"Imperva"),
    ],
    body_clues=[r"Incapsula incident", r"incapsula", r"Request unsuccessful"],
    status_codes=[403],
    evasions=[EVASION_UNICODE, EVASION_NULL_BYTE, EVASION_CASE_MIXING],
  ),
  WafSignature(
    name="AWS WAF",
    header_clues=[
      ("x-amzn-requestid", r".+"),
      ("x-amz-cf-id",      r".+"),
    ],
    body_clues=[r"AWS WAF", r"Request blocked"],
    status_codes=[403],
    evasions=[EVASION_HTML_ENCODE, EVASION_CASE_MIXING, EVASION_UNICODE],
  ),
  WafSignature(
    name="ModSecurity",
    header_clues=[
      ("server", r"mod_security"),
    ],
    body_clues=[
      r"ModSecurity",
      r"Not Acceptable!",
      r"406 Not Acceptable",
      r"This error was generated by Mod_Security",
    ],
    status_codes=[406, 403, 501],
    evasions=[EVASION_CASE_MIXING, EVASION_COMMENT_BREAK, EVASION_CHUNKED_TAGS, EVASION_NULL_BYTE],
  ),
  WafSignature(
    name="Sucuri",
    header_clues=[
      ("x-sucuri-id",      r".+"),
      ("x-sucuri-cache",   r".+"),
      ("server",           r"Sucuri"),
    ],
    body_clues=[r"Sucuri WebSite Firewall", r"sucuri.net", r"Access Denied - Sucuri"],
    status_codes=[403],
    evasions=[EVASION_UNICODE, EVASION_DOUBLE_ENCODE],
  ),
  WafSignature(
    name="F5 BIG-IP ASM",
    header_clues=[
      ("x-cnection",    r".+"),
      ("set-cookie",    r"TS[0-9a-f]{8}"),
    ],
    body_clues=[r"The requested URL was rejected", r"F5 Networks"],
    status_codes=[403],
    evasions=[EVASION_CHUNKED_TAGS, EVASION_NEWLINE, EVASION_CASE_MIXING],
  ),
  WafSignature(
    name="Barracuda",
    header_clues=[
      ("set-cookie", r"barra_counter_session"),
    ],
    body_clues=[r"Barracuda Web Application Firewall", r"barra_counter_session"],
    status_codes=[403],
    evasions=[EVASION_HTML_ENCODE, EVASION_DOUBLE_ENCODE],
  ),
  WafSignature(
    name="Wordfence",
    header_clues=[],
    body_clues=[r"Wordfence", r"Generated by Wordfence", r"This response was generated by Wordfence"],
    status_codes=[403],
    evasions=[EVASION_UNICODE, EVASION_CASE_MIXING],
  ),
  WafSignature(
    name="Fortinet FortiWeb",
    header_clues=[
      ("set-cookie", r"FORTIWAFSID"),
    ],
    body_clues=[r"FortiWeb", r"Application Firewall"],
    status_codes=[403],
    evasions=[EVASION_HTML_ENCODE, EVASION_CHUNKED_TAGS],
  ),
]

# Generic block signals (no specific WAF identified)
_GENERIC_BLOCK_BODIES = [
  r"Access Denied",
  r"Forbidden",
  r"Request Blocked",
  r"Security violation",
  r"Illegal request",
  r"Attack detected",
]

# Probe payload — something that should trigger most WAFs
_PROBE_PAYLOAD = "<script>alert(1)</script>"


# ---------------------------------------------------------------------------
# Detection
# ---------------------------------------------------------------------------

@dataclass
class WafResult:
  detected:    bool
  name:        Optional[str]
  evasions:    List[str]
  confidence:  str  # "high" | "medium" | "low" | "none"


def detect(injector, url: str, param: Optional[str] = None) -> WafResult:
  """
  Fire a probe request and fingerprint the WAF from the response.

  injector: engine.injector.Injector instance
  url:      target URL (GET probe if param is None)
  param:    if provided, inject as a GET parameter value
  """
  try:
    if param:
      probe_url = _inject_param(url, param, _PROBE_PAYLOAD)
    else:
      sep = "&" if "?" in url else "?"
      probe_url = f"{url}{sep}q={_PROBE_PAYLOAD}"

    resp = injector.get(probe_url)
  except Exception:
    return WafResult(detected=False, name=None, evasions=[EVASION_NONE], confidence="none")

  # Baseline: if we get a 2xx with the payload reflected, no WAF
  if resp.status_code < 400 and _PROBE_PAYLOAD.lower() in resp.text.lower():
    return WafResult(detected=False, name=None, evasions=[EVASION_NONE], confidence="none")

  headers_lower: Dict[str, str] = {k.lower(): v.lower() for k, v in resp.headers.items()}
  body = resp.text

  best_match: Optional[WafSignature] = None
  best_score = 0

  for sig in _SIGNATURES:
    score = 0

    for hdr, pattern in sig.header_clues:
      val = headers_lower.get(hdr, "")
      if val and re.search(pattern, val, re.IGNORECASE):
        score += 2

    for pattern in sig.body_clues:
      if re.search(pattern, body, re.IGNORECASE):
        score += 1

    if resp.status_code in sig.status_codes:
      score += 1

    if score > best_score:
      best_score = score
      best_match = sig

  if best_match and best_score >= 2:
    confidence = "high" if best_score >= 4 else "medium"
    return WafResult(
      detected=True,
      name=best_match.name,
      evasions=best_match.evasions,
      confidence=confidence,
    )

  # Generic block detected
  if resp.status_code in (403, 406, 429, 503):
    return WafResult(
      detected=True,
      name="Generic WAF",
      evasions=[EVASION_CASE_MIXING, EVASION_HTML_ENCODE, EVASION_UNICODE, EVASION_COMMENT_BREAK],
      confidence="low",
    )

  for pattern in _GENERIC_BLOCK_BODIES:
    if re.search(pattern, body, re.IGNORECASE):
      return WafResult(
        detected=True,
        name="Generic WAF",
        evasions=[EVASION_CASE_MIXING, EVASION_HTML_ENCODE, EVASION_UNICODE],
        confidence="low",
      )

  return WafResult(detected=False, name=None, evasions=[EVASION_NONE], confidence="none")


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _inject_param(url: str, param: str, value: str) -> str:
  """Replace the value of `param` in the URL query string with `value`."""
  parsed  = up.urlparse(url)
  qs      = up.parse_qs(parsed.query, keep_blank_values=True)
  qs[param] = [value]
  new_qs  = up.urlencode(qs, doseq=True)
  return up.urlunparse(parsed._replace(query=new_qs))
